### ISSUE TITLE
Reproduce problem

### ISSUE THREAD

**Issue by huangmozhi9527** [qinjr/RIM#2]
Dear authors,

Thanks for the amazing job!
I tried to reproduce this repo but found some problems.

It seems that I need to first do the feature engine to generate data for training.
However, when I run data_ppl/feateng.py. There are some configs missed ( e.g., joined_tabular_file, used_cnum, remap_c_pos_list, summary_dict_file).

So could you please provide the whole data, which can be directly used for training and testing?

**Comment by qinjr** [comment]
Thx for your interest.
Could you pls give the detailed error information?
The preprocessed data is hard to provide because of its size. So it is better to generate the data from the raw files.

**Comment by huangmozhi9527** [comment]
I don't know where to get the raw files, like joined_tabular_file = ../../data/tmall/feateng_data/joined_user_behavior.csv.
Could you provide these raw files?

**Comment by qinjr** [comment]
You could download the files from the links in the paper (Table 9) for each dataset. 
For Tmall dataset, I will provide the joined_user_behavior.csv (at https://pan.baidu.com/s/1_1YkZUSjEM1pqXgfkjVSUQ  password: kegx). It is a joined table comes from the raw files. 
Sorry for the inconvenience.

**Comment by huangmozhi9527** [comment]
Thank you very much! It's helpful.

**Comment by huangmozhi9527** [comment]
Sorry, I still meet a problem when ppl data.

Below is the error information:

Traceback (most recent call last):
  File "hori_split.py", line 234, in <module>
    cnf.get(dataset, 'sync_seq_dict_file'),
  File "/data/wangyuting/miniconda3/envs/wyt/lib/python3.8/configparser.py", line 792, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'sync_seq_dict_file' in section: 'tmall'

Could you please have a look?
Besides, could you please provide other joined_user_behavior files of Taobao, Alipay, ML-1M and LastFM?

**Comment by qinjr** [comment]
1. The config.ini file in `data_ppl` has been updated
2. For Taboo & Alipay, pls follow the given link in the paper. For Tmall & ML-1M & LastFM, pls follow the link (https://pan.baidu.com/s/1ZCs8n3X1iXWFglIiYQ9fGg  password:bq7j)

**Comment by huangmozhi9527** [comment]
Thanks for the response!
